FROM golang:latest

ARG REPO_NAME
ARG APP_NAME

WORKDIR /go/src/${REPO_NAME}/${APP_NAME}
COPY . .
RUN go get -d -u -v -t ./...
RUN go test ./...
RUN go get -d -u -v ./...
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
RUN mv ${APP_NAME} /publish