FROM alpine:latest
COPY ./ /src
WORKDIR /src

RUN apk update && apk add apache-ant git && ant jar
RUN mkdir /build \
      && cp -r /src/bin /build \
      && cp -r /src/conf /build \
      && cp -r /src/docs /build \
      && cp -r /src/lib /build \
      && cp -r /src/resources /build \
      && cp gen/toxic.jar /build/lib/
