apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.registry_file: /tmp/filebeat_registry
    filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - "/opt/toxic/log/*.log"
      multiline.pattern: '^[[:space:]]'
      multiline.match: after
      document_type: java-logs
    output.logstash:
      hosts: [ "logstash:5000" ]
      index: toxic
      timeout: 15
    logging.level: info