kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: toxic
spec:
  selector:
    matchLabels:
      name: toxic
  replicas: 1
  template:
    metadata:
      labels:
        name: toxic
    spec:
      securityContext: 
        runAsUser: 2000
        fsGroup: 2000
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: toxic-data-pvc
        - name: toxic-ssh-volume
          secret:
            secretName: toxic-ssh-secrets
            defaultMode: 0400
        - name: toxic-app-volume
          secret:
            secretName: toxic-app-secrets
        - name: filebeat-config
          configMap:
            name: filebeat-config
            items:
            - key: filebeat.yml
              path: filebeat.yml
      containers:
        - name: toxic
          image: stackct/toxic:1.0
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: data
              mountPath: /data
            - name: shared-log
              mountPath: /opt/toxic/log/
            - name: toxic-ssh-volume
              readOnly: true
              mountPath: /home/toxic/.ssh/
            - name: toxic-app-volume
              readOnly: true
              mountPath: /conf/
        - name: filebeat
          securityContext:
            runAsUser: 0
          image: docker.elastic.co/beats/filebeat:6.2.1
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: shared-log
              mountPath: /opt/toxic/log/
