{{- $fullName := include "toxic.fullname" . -}}
{{- $servicePort := .Values.toxic.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "toxic.name" . }}
    chart: {{ template "toxic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.oauth2.host }}/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.oauth2.host }}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-request-redirect: https://{{ .Values.toxic.ingress.host }}
spec:
{{- if .Values.toxic.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.toxic.ingress.host }}
      secretName: {{ .Values.toxic.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.toxic.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}

