apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.toxic.storage.storageClass }}
spec:
  capacity:
    storage: {{ .Values.toxic.storage.storageSize }}
  storageClassName: {{ .Values.toxic.storage.storageClass }}
  azureFile:
    secretName: azure-secret
    shareName: {{ .Values.toxic.storage.shareName }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain