make.target=all
artifactsDir=`"${memory.job.jobDir}/artifacts"`
job.trigger.repoCommit=true
job.init.script.0=new File("${memory['project.workDir']}/gen/job").mkdirs()
job.init.script.1=new File("${memory['project.workDir']}/gen/job/build.groovy").text="assert 0 == execWithEnv(['make', '${memory['make.target']}'], ['ARTIFACTS_DIR': '${memory.artifactsDir}'], 14400, '${memory['project.workDir']}', null)"
doDir=`"${memory['project.workDir']}/gen/job/build.groovy"`
doDir1=`"${memory['project.workDir']}/toxic/setup"`
doDir2=`"${memory['project.workDir']}/toxic/tests"`
doDir3=`"${memory['project.workDir']}/toxic/teardown"`
job.end.script.0=memory['job'].parseJUnitXmlFilesInDir(new File("${memory['project.workDir']}/gen/test"))
