package log

import org.apache.log4j.*
import org.apache.log4j.spi.*

/**
 * Allow a single appender to limit the log messages that it logs by the thread
 * it was created on. Adding this appender, wrapped around a normal appender, means
 * that all threads that run through this same code will only pass on to the wrapped
 * appender the log messages generated by that thread.
 */
class StickyThreadAppender implements Appender {
  @Delegate Appender appender

  def creatingThread

  def StickyThreadAppender(appender) {
    this.appender = appender
    this.creatingThread = Thread.currentThread()
  }

  void append(LoggingEvent event) {
    if (creatingThread == Thread.currentThread()) {
      appender.append(event)
    }
  }
}

