name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with: 
          distribution: adopt
          java-version: '8'
      - run: ant